#!/bin/bash
set -eux

source ./hooks/versions.sh

for pg_version in ${!VERSIONS[@]}; do
  docker build \
         --build-arg "ALPINE_VERSION=${VERSIONS[$pg_version]}" \
         --tag "postgres-backup-s3:$pg_version" \
         .
done

